[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyink]
# Match your VS Code and Makefile configuration
line-length = 80
preview = true
# skip-string-normalization = true
